version: '3.8'

services:
  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: demo:0.0.1
    container_name: demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:notedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATA_REDIS_HOST: my-redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
